#!/usr/bin/env sh

set -e
test -n "$DEBUG" && set -x

for CMD in git jq grep; do
  if ! command -v "$CMD" 1>/dev/null 2>&1; then
    echo "Could not find $CMD executable" 1>&2
    exit 69
  fi
done

TMP_REPO=/tmp/ed4d48ee-2fa3-4d1e-a796-613acd747554

if [ ! -d "$TMP_REPO" ]; then
  git clone --depth=1 https://github.com/oxalica/rust-overlay.git "$TMP_REPO" 1>&2
fi

cleanup() {
  rm -rf "$TMP_REPO"
}

trap cleanup INT TERM

VERSION_LIST='[]'

add_version() {
  VERSION_INFO="$(jq --null-input \
    --arg channel "$1" \
    --arg version "$2" \
    '$ARGS.named')"

  VERSION_LIST="$(echo "$VERSION_LIST" | jq ". += [$VERSION_INFO]")"
}

add_version stable latest
add_version beta latest
add_version nightly latest

for FILE in "$TMP_REPO/manifests/stable"/*; do
  VERSION="$(basename "$FILE" .nix)"

  if [ "$(echo "$VERSION" | grep -Ec "^[0-9]+\.[0-9]+\.[0-9]+$")" -eq 0 ]; then
    continue
  fi

  if [ "$(printf '%s\n%s' '1.33.0' "$VERSION" | sort -V | head -n 1)" != "1.33.0" ]; then
    continue
  fi

  add_version stable "$VERSION"
done

echo "$VERSION_LIST"

cleanup
