name: Update All

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'

jobs:
  update-all:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0
          path: nix-develop-rust
      - uses: actions/checkout@v4
        with:
          repository: oxalica/rust-overlay
          path: rust-overlay
      - uses: cachix/install-nix-action@v23
      - run: |
          nix --extra-experimental-features "nix-command flakes" shell \
            nixpkgs#git \
            nixpkgs#jq \
            nixpkgs#envsubst
          cd "$GITHUB_WORKSPACE/nix-develop-rust"
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          export OXALICA_RUST_OVERLAY="$GITHUB_WORKSPACE/rust-overlay"
          sh scripts/mk-version-list > /tmp/rust-versions.json
          sh scripts/mk-flake-nix templates/flake.nix flake.nix < /tmp/rust-versions.json
          sh scripts/mk-flake-lock < /tmp/rust-versions.json
